BBandB/BBandB/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from APP1 import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include

urlpatterns = [

    path('admin/', admin.site.urls),


#admin login,logout..user signup,login,otp,logout
    
    path('adminn/', views.admin_login,name='admin'),
    path('admin_logout/',views.admin_logout,name='admin_logout'),
    path('signup/', views.signupPage, name='signup'),
    path('otp/', views.verify_signup, name='otp'),
    path('category/',views.category, name = 'category'),
    path('addc/',views.add_category,name= 'add_category'),
    path('edit/<int:product_id>/',views.editproduct,name='edit_product'),
    path('product/<int:id>/update/', views.update, name='update'),
    path('product/<int:product_id>/delete/', views.delete_product, name='delete_product'),
    path('customer/<int:customer_id>/block/', views.block_customer, name='block_customer'),
    path('customer/<int:customer_id>/unblock/', views.unblock_customer, name='unblock_customer'),
    path('category/<int:id>/update_category/', views.update_category, name='update_category'),
    path('category/<int:category_id>/delete/', views.delete_category, name='delete_category'),
    path('category/<int:category_id>/edit/', views.editcategory, name='edit_category'),
 

    
#dashboard,customer,order,product
    path('dashboard/', views.dashboard,name='dashboard'),
    path('Customer/',views.customers,name='customer'),
    path('products/',views.product,name='products'),
    path('add/', views.add_product, name='add_product'),

     


#user side
    path('',views.home,name='home'),
    path('login', views.loginPage, name='login'),
    path('logout/',views.logoutPage,name='logout'),
    path('userproduct/',views.userproductpage,name='userproduct'),
    path('verify_otp/',views.verify_signup,name='verify_signup'),
    path('social-auth/', include('social_django.urls', namespace = 'social')),


# app2
    path('', include('SHOPPER.urls')),



]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

BBandB/SHOPPER/models.py
from django.db import models
from APP1.models import Product,Customer
from datetime import date


class Cart(models.Model):
    user           =     models.ForeignKey(Customer, on_delete=models.CASCADE,null=True,blank=True)
    product        =     models.ForeignKey(Product,on_delete=models.CASCADE,null=True,blank=True)
    quantity       =     models.IntegerField(default=0)
    image          =     models.ImageField(upload_to='products',null=True, blank=True )
    device              = models.CharField(max_length=255, null=True, blank=True)

    @property
    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
          return f"Cart: {self.user.username} - {self.product} - Quantity: {self.quantity}"

     
class Address(models.Model):
    user           =     models.ForeignKey(Customer,on_delete=models.CASCADE)
    first_name     =     models.CharField(max_length=50,null=False,blank=True)
    last_name      =     models.CharField(max_length=50,null=False,blank=True)
    email          =     models.EmailField()
    number         =     models.CharField(max_length=10)
    address1       =     models.CharField(max_length=200)
    address2       =     models.CharField(max_length=200)
    country        =     models.CharField(max_length=15)
    state          =     models.CharField(max_length=15)
    city           =     models.CharField(max_length=15)
    zip_code       =     models.IntegerField()
   
    



    def __str__(self):
        return f"{self.first_name} {self.last_name}"
    
    
class Coupon(models.Model):
    coupon_code     =  models.CharField(max_length=100)
    expired         =  models.BooleanField(default=False)
    discount_price  =  models.PositiveIntegerField(default=100)
    minimum_amount  =  models.PositiveIntegerField(default=500)
    expiry_date     =  models.DateField(null=True,blank=True)

    def __str__(self):
        return self.coupon_code
    


class Order(models.Model):

    ORDER_STATUS = (
        ('pending', 'Pending'),
        ('processing','processing'),
        ('shipped','shipped'),
        ('delivered','delivered'),
        ('completed', 'Completed'),
        ('cancelled', 'Cancelled'),
        ('refunded','refunded'),
        ('on_hold','on_hold')

    )

    user           =   models.ForeignKey(Customer, on_delete=models.CASCADE) 
    address        =   models.ForeignKey(Address, on_delete=models.CASCADE)
    product        =   models.ForeignKey(Product, on_delete=models.CASCADE, null=True, blank=True)
    amount         =   models.CharField(max_length=100)  
    payment_type   =   models.CharField(max_length=100)  
    status         =   models.CharField(max_length=100, choices=ORDER_STATUS, default='pending' )  
    quantity       =   models.IntegerField(default=0, null=True, blank=True)
    image          =   models.ImageField(upload_to='products', null=True, blank=True)
    date           =   models.DateField(default=date.today)
    coupon         =   models.ForeignKey(Coupon, on_delete=models.SET_NULL, null=True, blank=True)

    
    def __str__(self):
        return f"Order #{self.pk} - {self.product}"

class OrderItem(models.Model):
    order          =   models.ForeignKey(Order,on_delete=models.CASCADE)
    product        =   models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity       =   models.IntegerField(default=1)
    image          =   models.ImageField(upload_to='products', null=True, blank=True)

    def __str__(self):
        return str(self.id)


     
class Images(models.Model):
    product     =  models.ForeignKey(Product, on_delete=models.CASCADE)
    images      =  models.ImageField(upload_to='products')


class Wishlist(models.Model):
    user = models.ForeignKey(Customer, on_delete=models.CASCADE,null=True,blank=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image  = models.ImageField(upload_to='products', null=True,blank=True)
    device = models.CharField(max_length=255, null=True,blank=True)

    def __str__(self):
        return f"Wishlist:{self.user.username}-{self.product}"
    

    

BBandB/templates/admin_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="login.css">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

    <title>Login</title>
    <style>
        *{
            padding: 0;
            margin: 0;
            box-sizing: border-box;
        }
        body{
            background-color: rgb(236, 244, 244);
            background-image: url("#");
            background-size: cover;
            background-repeat: no-repeat;
            background-attachment: scroll;



        }

        .row{
            background-color: white;
            border-radius: 30px;
            box-shadow: 12px 33px 33px gray;
           

        }

        img{
            border-top-left-radius: 25px;
            border-bottom-left-radius: 25px;
        }
        .btn1{
            border: none;
            outline: none;
            height: 50px;
            width: 100%;
            background-color: rgb(12, 168, 160);
            color: rgb(245, 236, 236);
            border-radius: 4px;
            font-weight: bold;
            border-radius: 10px;
            
        }
        .btn1:hover{
            background: white;
            border: 1px solid;
            color: black;   
        }

        .form {
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 90vh;

        }

       

        
        @media screen and (max-width: 768px) {
            body {
                background-size: contain;
            }
        }

        


        

       
    </style>
</head>
<body>
    <section class="form my-4 mx -5 mt-5">
        {% csrf_token %}
        <div class="container">
            <div class="row no-gutters">
                <div class="col-lg-5">
                    <img src="" class="img-fluid" alt="">
                </div>

                <div class="col-lg-7 px-5 pt-5 ">
                    <form action="" method="post">
                        {% csrf_token %} 

                        <h2 style="text-align: center; margin-right:250px;">Admin login</h2>

                        <div class="form-row">
                            <div class="col-lg-7">
                                
                                <input type="email" placeholder="Enter your email-id" name="username" class="form-control my-3 p-4">

                            </div>

                        </div>

                        <div class="form-row">
                            <div class="col-lg-7">
                                
                                <input type="password" placeholder="Enter your password" name="pass" class="form-control">

                                {% if messages %}
                                    <ul class="messages text-danger">
                                        {% for message in messages %}
                                            <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                                        {% endfor %}
                                    </ul>
                                {% endif %}

                            </div>

                        </div>

                        


                        <div class="form-row">
                            <div class="col-lg-7">
                                
                                <button type="submit" class="btn1 mt-4 mb-3">Login</button>

                                <!-- <a href="">Forgot password</a> -->

                                <!-- <p>Don't have an account? <a href="{% url 'signup' %}">Register here</a></p>
         -->
    
                                
                            </div>

                          
                        </div>

                       
                    </form>



                </div>

             </div>
 
        </div>


    </section>

    

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html> 

BBandB/templates/admin_order_details.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Dashboard</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&display=swap" rel="stylesheet">
    
    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'admin/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'admin/css/style.css' %}" rel="stylesheet">
    <!-- chart js -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

</head>

<body>
    <div class="container-xxl position-relative bg-white d-flex p-0">
        
        <!-- Sidebar Start -->
        <div class="sidebar pe-4 pb-3">
            {% include 'snippets/admin_sidebar.html' %}
        </div>
        <!-- Sidebar End -->


        <!-- Content Start -->
        <div class="content">
            <!-- Navbar Start -->
            <nav class="navbar navbar-expand bg-light navbar-light sticky-top px-4 py-0">
                <a href="index.html" class="navbar-brand d-flex d-lg-none me-4">
                    <!-- <h2 class="text-primary mb-0"><i class="fa fa-hashtag"></i></h2> -->
                </a>
                <a href="#" class="sidebar-toggler flex-shrink-0">
                    <i class="fa fa-bars"></i>
                </a>
                <form class="d-none d-md-flex ms-4">
                    <input class="form-control border-0" type="search" placeholder="Search">
                </form>
                
                <div class="navbar-nav align-items-center ms-auto">
                    <div class="nav-item dropdown">
                       
                    </div>
                    <div class="nav-item dropdown">
                        
                    </div>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            <img class="rounded-circle me-lg-2" src="{% static 'admin/img/adm.png ' %}" alt="" style="width: 40px; height: 40px;">
                            <span class="d-none d-lg-inline-flex">Neenu</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">
                            <a href="#" class="dropdown-item">My Profile</a>
                            <a href="#" class="dropdown-item">Settings</a>
                            <a href="{% url 'admin_logout' %}" class="dropdown-item">Log Out</a>
                        </div>
                    </div>
                </div>
            </nav>
            
            <div class="container mt-4">
                <h3>Order Details</h3>
              
                <form enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="modal-body">					
                        <div class="form-group">
                            <label>User_name</label>
                            <input name="" type="text" class="form-control" value="{{ order.user.username }}"  readonly>
                        </div>
                        <div class="form-group">
                            <label>Address</label>
                            <input name="" type="text" class="form-control"  value= "{{ order.address.address1  }}" readonly>
                        </div>

                        <div class="form-group">
                            <label>Phone number</label>
                            <input name="" type="number" class="form-control"  value= "{{ order.address.number }}"readonly>
                        </div>

                        <div class="form-group">
                            <label>Product id</label>
                            {% if order.orderitem_set.all %}
                                {% for order_item in order.orderitem_set.all %}
                                    <input name="" type="text" class="form-control"  value= "{{ order_item.product.id  }}" readonly>
                                {% endfor %}
                            {% else %}
                                <p class="mb-0 fw-normal">No products</p>
                            {% endif %}
                        </div>

                        <div class="form-group">
                            <label>Product name</label>
                            
                            {% if order.orderitem_set.all %}
                                {% for order_item in order.orderitem_set.all %}
                                    <input name="" type="text" class="form-control"  value= "{{ order_item.product.product_name }}" readonly>
                                {% endfor %}
                            {% else %}
                                <p class="mb-0 fw-normal">No product name</p>
                            {% endif %}
                        </div>
                        <div class="form-group">
                            <label>Total amount</label>
                            <input name="" type="number" class="form-control"  value= "{{ order.amount  }}" readonly>
                        </div>

                        {% if order.coupon %}
                            <div class="form-group">
                                <label>Coupon amount</label>
                                <input name="coupon_amount" type="number" class="form-control" value="{{ order.coupon.discount_price }}" readonly>
                            </div>
                        {% endif %}

                        <div class="form-group">
                            <label>Payment type</label>
                            <input name="" type="text" class="form-control"  value= "{{ order.payment_type }}" readonly>
                        </div>

                        <div class="form-group">
                            <label>Date of order</label>
                            <input name="" type="text" class="form-control"  value= "{{ order.date }}" readonly>
                        </div>

                        <div style="max-width: 100px; max-height: 100px;" class="form-group">
                            <label>Image</label>
                            <div class="d-inline-flex">
                                {% if order.orderitem_set.all %}
                                    {% for order_item in order.orderitem_set.all %}
                                        <img src="{{ order_item.image.url }}" alt="" width="60" style="margin-right: 10px;">
                                    {% endfor %}
                                {% else %}
                                    <p class="mb-0 fw-normal">No images</p>
                                {% endif %}
                            </div>
                        </div>
                    </div>      
                </form>
                
            </div>
        </div>
        <!-- Content End -->
    </div>
    <!-- Bootstrap JS Bundle -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

BBandB/templates/customer_order.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<style>

    .dropdown {
    position: relative;
    display: inline-block;
    }

    .dropdown-content {
    display: none;
    position: absolute;
    z-index: 1;
    }

    .dropdown:hover .dropdown-content {
    display: block;
    }



</style>

<head>
    <meta charset="utf-8">
    <title>Orders</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet"> 

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'home/lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'home/css/style.css' %}" rel="stylesheet">
</head>

<body>
    <!-- footer start -->
    <div class="container-fluid">
        <div class="row bg-secondary py-2 px-xl-5">
            <div class="col-lg-6 d-none d-lg-block">
                <div class="d-inline-flex align-items-center">
                    <a class="text-dark" href="">FAQs</a>
                    <span class="text-muted px-2">|</span>
                    <a class="text-dark" href="">Help</a>
                    <span class="text-muted px-2">|</span>
                    <a class="text-dark" href="">Support</a>
                </div>
            </div>
            <div class="col-lg-6 text-center text-lg-right">
                <div class="d-inline-flex align-items-center">
                    <a class="text-dark px-2" href="">
                        <i class="fab fa-facebook-f"></i>
                    </a>
                    <a class="text-dark px-2" href="">
                        <i class="fab fa-twitter"></i>
                    </a>
                    <a class="text-dark px-2" href="">
                        <i class="fab fa-linkedin-in"></i>
                    </a>
                    <a class="text-dark px-2" href="">
                        <i class="fab fa-instagram"></i>
                    </a>
                    <a class="text-dark pl-2" href="">
                        <i class="fab fa-youtube"></i>
                    </a>
                </div>
            </div>
        </div>
        <div class="row align-items-center py-3 px-xl-5">
            <div class="col-lg-3 d-none d-lg-block">
                <a href="{% url 'home' %}" class="text-decoration-none">
                    <h5 class="m-0 display-5 font-weight-semi-bold"><img src="{% static 'home/img/mainlogo.png' %}" style="width: 30%; height: 30%;" alt="Image"></span>Batter,Butter&Beyond</h5>
                </a>
                </a>
                </a>
            </div>
            <div class="col-lg-6 col-6 text-left">
                <form method ="get" action="{% url 'search' %}">
                    <div class="input-group">
                        <input type="text" class="form-control" name="q" placeholder="Search for products">
                        <div class="input-group-append">
                            <button type="submit" class="btn btn-primary">
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </div>   
                </form>
            </div>
            <div class="col-lg-3 col-6 text-right">
                <div class="dropdown">
                    <a href="{% url 'edit_profile' %}" class="btn border dropdown-toggle" id="profileDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-user-circle fa-lg text-primary"></i>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="profileDropdown">
                      <!-- Dropdown menu items -->
                      <a class="dropdown-item" href="{% url 'edit_profile' %}">Profile</a>
                      <a class="dropdown-item" href="{% url 'customer_order' %}">Orders</a>
                      <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                    </div>
                </div>
                
                <a href="{% url 'wishlist' %}" class="btn border">
                    <i class="fas fa-heart text-primary"></i>
                    <!-- <span class="badge">0</span> -->
                </a>
                <a href="{% url 'cart' %}" class="btn border">
                    <i class="fas fa-shopping-cart text-primary"></i>
                    <!-- <span class="badge">0</span> -->
                </a>
            </div>
        </div>
    </div>
     <!-- footer end -->
   



<div class="table-responsive container mt-5">
   
    <table class="table table-sm text-start align-middle table-hover mb-0">
        <thead>
            <tr class="text-dark">
                <th scope="col">Order Id</th>
                <th scope="col">Product</th>
                <th scope="col">Quantity</th>
                <th scope="col">Amount</th>
                <th scope="col">Payment Type</th>
                <th scope="col">Date</th>
                <th scope="col">Status</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            {% for order in orders %}
            <tr {% if order.status == 'cancelled' %}style=" background-color: #ffcccc;"{% endif %}>  
                <td>{{ order.id }}</td>
                <td>
                    {% if order.orderitem_set.all %}
                        {% for order_item in order.orderitem_set.all %}
                            <div class="mb-2">
                                <img src="{{ order_item.image.url }}" alt="" width="60">
                            </div>
                        {% endfor %}
                    {% else %}
                        <p class="mb-0 fw-normal">No products</p>
                    {% endif %}
                
                <td class="border-bottom-0">
                    {% if order.orderitem_set.all %}
                        {% for order_item in order.orderitem_set.all %}
                            <h6 class="fw-semibold mb-1">
                                {{ order_item.product.product_name }} (x{{ order_item.quantity }})
                            </h6>
                        {% endfor %}
                    {% else %}
                        <p class="mb-0 fw-normal">No products</p>
                    {% endif %}
                </td>
                <td>{{ order.amount }}</td>
                <td>{{ order.payment_type }}</td>
                <td>{{ order.date }}</td>
                <td>{{ order.status }}</td>
                <td>
                    {% if order.status == 'pending' or order.status == 'processing' %}
                    <form action="{% url 'cancel_order' order.id %}" method="POST" name="cancel_form">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger btn-sm">Cancel</button>
                    </form>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
   
</div>
 <!-- Footer Start -->
{% include 'snippets/footer.html' %}
<!-- Footer End -->

<a href="#" class="btn btn-primary back-to-top"><i class="fa fa-angle-double-up"></i></a>


<!-- JavaScript Libraries -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'home/lib/easing/easing.min.js' %}"></script>
<script src="{% static 'home/lib/owlcarousel/owl.carousel.min.js' %}"></script>

<!-- Contact Javascript File -->
<script src="{% static 'home/mail/jqBootstrapValidation.min.js' %}"></script>
<script src="{% static 'home/mail/contact.js' %}"></script>

<!-- Template Javascript -->
<script src="{% static 'home/js/main.js' %}"></script>

</body>